import { describe, it, expect } from 'vitest';
import { resolveFsdPaths } from '../../src/lib/naming/resolvePaths.js';
import { processTemplate } from '../../src/lib/templates/templateLoader.js';
import { prepareActionVariables } from '../../src/lib/preset/actionExecution.js';

describe('Integration: Component Generation Flows', () => {
    it('should simulate a complete component and styles generation flow', () => {
        // 1. Define component metadata
        const metadata = {
            layer: 'feature' as const,
            slice: 'ProductCatalog',
            component: 'ProductGrid',
            author: 'EcommerceTeam',
            theme: 'modern',
        };

        // 2. Resolve paths
        const paths = resolveFsdPaths('src', metadata.layer, metadata.slice, metadata.component);

        // 3. Prepare variables
        const action = {
            type: 'component' as const,
            layer: metadata.layer,
            slice: metadata.slice,
            name: metadata.component,
            template: 'ui-grid',
            variables: {
                gridColumns: '4',
                itemSpacing: '16px',
            },
        };

        const vars = prepareActionVariables(action, metadata.component, {
            author: metadata.author,
            theme: metadata.theme,
        });

        // 4. Generate component file content
        const componentTemplate = `
import { FC } from 'react';
import styles from './{{componentName}}.styles';

/**
 * {{componentName}} - Generated by {{author}}
 * Theme: {{theme}}
 */
export const {{componentName}}: FC = () => {
  return (
    <div className={styles.grid} data-columns="{{gridColumns}}">
      {/* Grid content */}
    </div>
  );
};
    `.trim();

        const componentContent = processTemplate(componentTemplate, vars);

        // 5. Generate styles file content
        const stylesTemplate = `
.grid {
  display: grid;
  grid-template-columns: repeat({{gridColumns}}, 1fr);
  gap: {{itemSpacing}};
}
    `.trim();

        const stylesContent = processTemplate(stylesTemplate, vars);

        // 6. Verify generated content
        expect(componentContent).toContain('export const ProductGrid: FC');
        expect(componentContent).toContain('ProductGrid - Generated by EcommerceTeam');
        expect(componentContent).toContain('Theme: modern');
        expect(componentContent).toContain('data-columns="4"');
        expect(componentContent).toContain("import styles from './ProductGrid.styles'");

        expect(stylesContent).toContain('grid-template-columns: repeat(4, 1fr)');
        expect(stylesContent).toContain('gap: 16px');

        // 7. Verify paths
        expect(paths.componentPath).toBe('src/features/ProductCatalog/ui/ProductGrid');
    });

    it('should correctly resolve paths for multiple components within the same slice', () => {
        const rootDir = 'src';
        const layer = 'entity';
        const slice = 'User';

        const component1 = 'UserCard';
        const component2 = 'UserAvatar';

        const paths1 = resolveFsdPaths(rootDir, layer, slice, component1);
        const paths2 = resolveFsdPaths(rootDir, layer, slice, component2);

        expect(paths1.uiPath).toBe('src/entities/User/ui');
        expect(paths1.componentPath).toBe('src/entities/User/ui/UserCard');

        expect(paths2.uiPath).toBe('src/entities/User/ui');
        expect(paths2.componentPath).toBe('src/entities/User/ui/UserAvatar');

        expect(paths1.uiPath).toBe(paths2.uiPath);
        expect(paths1.slicePath).toBe(paths2.slicePath);
    });

    it('should handle shared components with overridden templates and variables', () => {
        const action = {
            type: 'component' as const,
            layer: 'shared' as const,
            slice: 'Button',
            name: 'Button',
            template: 'ui/custom-button',
            variables: {
                variant: 'ghost',
                animate: 'true'
            }
        };

        const paths = resolveFsdPaths('src', action.layer, action.slice, 'Button');
        const vars = prepareActionVariables(action, 'Button', { globalTheme: 'dark' });

        const template = `
import { FC } from 'react';
import { motion } from 'framer-motion';

export const Button: FC = () => {
  return (
    <motion.button 
      data-variant="{{variant}}" 
      data-theme="{{globalTheme}}"
      animate={ {{animate}} }
    >
      Click Me
    </motion.button>
  );
};
    `.trim();

        const result = processTemplate(template, vars);

        expect(paths.uiPath).toBe('src/shared/Button'); // Shared has no ui subdir
        expect(result).toContain('data-variant="ghost"');
        expect(result).toContain('data-theme="dark"');
        expect(result).toContain('animate={ true }');
    });

    it('should resolve paths and process templates for a User entity (Dynamic Names)', () => {
        // This test combines resolveFsdPaths, prepareActionVariables, and processTemplate
        const paths = resolveFsdPaths('src', 'entity', 'User', 'UserCard');

        const action = {
            type: 'component' as const,
            layer: 'entity' as const,
            slice: 'User',
            name: 'UserCard',
            template: 'preset/test/entity/ui',
            variables: {
                icon: 'user',
                color: 'blue',
            },
        };

        const vars = prepareActionVariables(action, 'User', { author: 'TeamA' });

        const template = `
      import { {{componentName}} } from './{{componentName}}';
      export const path = '{{componentPath}}';
      export const author = '{{author}}';
      export const icon = '{{icon}}';
    `.trim();

        const result = processTemplate(template, {
            ...vars,
            componentPath: paths.componentPath,
        });

        expect(result).toContain("import { User } from './User'");
        expect(result).toContain("path = 'src/entities/User/ui/UserCard'");
        expect(result).toContain("author = 'TeamA'");
        expect(result).toContain("icon = 'user'");
    });
});
