import { describe, it, expect } from 'vitest';
import { resolveFsdPaths } from '../../src/lib/naming/resolvePaths.js';
import { processTemplate } from '../../src/lib/templates/templateLoader.js';
import { prepareActionVariables } from '../../src/lib/preset/actionExecution.js';
import { ACTION_TYPES } from '../../src/lib/constants.js';

describe('Integration: React Block Granular Generation', () => {
    it('should simulate a hook generation flow', () => {
        const action = {
            type: ACTION_TYPES.HOOK,
            layer: 'entity' as const,
            slice: 'User',
            name: 'useUser',
            template: 'api/get',
            variables: {
                endpoint: '/api/v1/user'
            }
        };

        const vars = {
            ...prepareActionVariables(action, 'User', { author: 'Dev' }),
            componentName: action.name
        };
        const paths = resolveFsdPaths('src', action.layer, action.slice, action.name);

        const hookTemplate = `
/**
 * Hook generated by {{author}}
 */
export const {{componentName}} = () => {
    const url = '{{endpoint}}';
    return { url };
};
        `.trim();

        const result = processTemplate(hookTemplate, vars);

        expect(paths.componentPath).toBe('src/entities/User/ui/useUser');
        expect(result).toContain('export const useUser = () =>');
        expect(result).toContain('const url = \'/api/v1/user\'');
        expect(result).toContain('Hook generated by Dev');
    });

    it('should simulate a styles-only generation flow', () => {
        const action = {
            type: ACTION_TYPES.STYLES,
            layer: 'feature' as const,
            slice: 'Search',
            name: 'SearchField',
            template: 'ui/styles',
            variables: {
                primaryColor: '#0070f3'
            }
        };

        const vars = prepareActionVariables(action, 'Search', { author: 'Designer' });
        const paths = resolveFsdPaths('src', action.layer, action.slice, action.name);

        const stylesTemplate = `
export const styles = {
    root: {
        color: '{{primaryColor}}',
        // Generated by {{author}}
    }
};
        `.trim();

        const result = processTemplate(stylesTemplate, vars);

        expect(paths.componentPath).toBe('src/features/Search/ui/SearchField');
        expect(result).toContain('color: \'#0070f3\'');
        expect(result).toContain('Generated by Designer');
    });
});
